### PR TITLE
Add New Tokens & Exchanges

### PR DESCRIPTION
**Pull request by JettScythe**

### CODE REVIEW

**Comment by zquestz** [comment]
Would add, but we need a nice icon for it. There is an assets directory and we need an image. =)

**Comment by JettScythe** [comment]
I'm not the creator of this token, I just wanted to see it in the wallet. I'll reach out and see if I can grab an icon for it. If so, will add another commit. Mind if I leave this PR open in the meantime?

**Comment by zquestz** [comment]
Leave it open, and if you want to be extra awesome, lets add the other cool tokens.

- axiebch
- mist
- xmist
- pota (?)

Not sure if there are more... but I keep seeing new ones. =)

**Comment by zquestz** [comment]
Sizes of the asset files looks good, but we really should try to make sure they are just the icon, and not the background. These will look very square compared to everything else. Not sure exactly the best way to handle that.

**Comment by JettScythe** [comment]
I'll try to edit them once I get some free time, no worries.

**Comment by zquestz** [comment]
Sounds like a plan, and we still need an icon for the pet rock =P

**Comment by zquestz** [comment]
BTW the community icons for mistswap, they look like they are white? Do they look ok on the page?

**Comment by JettScythe** [comment]
Ngl I havent opened it up to check. I'll edit them tomorrow morning to be black.

**Comment by zquestz** [comment]
This is looking good, you done with your changes?

**Comment by JettScythe** [comment]
yup!

**Pull request merged**
